name: Rust Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  COVERAGE_THRESHOLD: 80
  RUST_LOG: debug
  RUST_BACKTRACE: full

# This stops any running jobs when a new commit is pushed
# Reference: https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare-ci-image:
    uses: ./.github/workflows/prepare-ci-image.yml
    permissions:
      packages: write
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}-ci
      dockerfile-context: images/ci/
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: prepare-ci-image
    container:
      image: ${{ needs.prepare-ci-image.outputs.image }}
      options: --user 0
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: build-${{ hashFiles('Cargo.lock') }}

      - name: Run tests
        run: cargo test --locked


  quality-check:
    runs-on: ubuntu-latest
    needs: prepare-ci-image
    container:
      image: ${{ needs.prepare-ci-image.outputs.image }}
      options: --user 0

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: quality-${{ hashFiles('Cargo.lock') }}
        
      - name: Check Rust formatting
        if: ${{ !cancelled() }}
        run: cargo +nightly fmt --check

      - name: Check for clippy warnings
        if: ${{ !cancelled() }}
        run: cargo clippy --locked --workspace --all-targets --no-deps --all-features -- -D warnings

  code-coverage:
    runs-on: ubuntu-latest
    needs: prepare-ci-image
    container:
      image: ${{ needs.prepare-ci-image.outputs.image }}
      options: --user 0
    env:
      COVERAGE_DIR: /tmp/coverage
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: coverage-${{ hashFiles('Cargo.lock') }}

      - name: Generate code coverage
        run: |
          cargo +nightly llvm-cov --all-features --workspace --locked --branch
          cargo +nightly llvm-cov report --html --output-dir ${{ env.COVERAGE_DIR }}/html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: ${{ env.COVERAGE_DIR }}/html

      - name: Fail if coverage below threshold
        run: cargo +nightly llvm-cov report --fail-under-lines=${{ env.COVERAGE_THRESHOLD }}

  docs:
    runs-on: ubuntu-latest
    needs: prepare-ci-image
    container:
      image: ${{ needs.prepare-ci-image.outputs.image }}
      options: --user 0
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: docs-${{ hashFiles('Cargo.lock') }}

      - name: Generate docs
        if: ${{ !cancelled() }}
        run: cargo doc --locked --lib --no-deps --all-features --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

      - name: Upload Docs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: docs
          path: target/doc

  call-security-audit:
    needs: prepare-ci-image
    uses: ./.github/workflows/audit.yml
    with:
      image: ${{ needs.prepare-ci-image.outputs.image }}
