name: Renovate

on:
  schedule:
    # Run hourly
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
