name: Renovate

on:
  schedule:
     - cron: '0 */12 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ github.event.inputs.debug == 'true' && 'debug' || 'info' }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
