name: Renovate

on:
  schedule:
    # Run hourly
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean


jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ github.event.inputs.debug == 'true' && 'debug' || 'info' }}
          RENOVATE_CONFIG_FILE: .github/renovate.json
